[workspace]
members = ["sync", "migration"]
resolver = "2"
[workspace.package]
authors = ["Boern <boern.x@gmail.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[profile.release]
debug = true
lto = true
opt-level = 'z'
