database_url = 'postgres://postgres:omnity_go@localhost:5432/omnity'
dfx_network = 'https://ic0.app'
log_config = './log4rs.yaml'
# dfx config vars
dfx_identity = './test.pem'
omnity_hub_canister_id = '7wupf-wiaaa-aaaar-qaeya-cai'
omnity_customs_bitcoin_canister_id = '7rvjr-3qaaa-aaaar-qaeyq-cai'
omnity_routes_icp_canister_id = '7ywcn-nyaaa-aaaar-qaeza-cai'