//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "launchpad")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub launchpad: String,
	pub cainister_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::token_meta::Entity")]
	TokenMeta,
}

impl Related<super::token_meta::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::TokenMeta.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
