//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use super::sea_orm_active_enums::TicketType;
use super::sea_orm_active_enums::TxAction;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pending_ticket")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
	pub ticket_id: String,
	pub ticket_type: TicketType,
	pub ticket_time: i64,
	pub src_chain: String,
	pub dst_chain: String,
	pub action: TxAction,
	pub token: String,
	pub amount: String,
	pub sender: Option<String>,
	pub receiver: String,
	pub memo: Option<String>,
	pub ticket_index: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
