# @hostname = localhost
@hostname = 34.44.123.28
@port = 8080
@host = {{hostname}}:{{port}}

### query all the chains metadata
GET http://{{host}}/api/rest/chain_meta
### query a chain metadata by its chain_id	
GET http://{{host}}/api/rest/chain_meta/eICP
### query a chain metadata by its canister_id	
GET http://{{host}}/api/rest/chain_meta/canister/x7lb2-jqaaa-aaaag-qjrkq-cai


### query all the tokens metadata
GET http://{{host}}/api/rest/token_meta
### query a token metadata by its token_id
GET http://{{host}}/api/rest/token_meta/ICP-icrc-GOOD•GOD


### query the ticket detail by its ticket_id
GET http://{{host}}/api/rest/ticket/ugaqt-wqaaa-aaaar-qafgq-cai_101

### query tickets with pagination
GET http://{{host}}/api/rest/tickets/paginated?limit=6&offset=0

### query tickets by src_chain
GET http://{{host}}/api/rest/tickets/chain/ICP

### query tickets by token
GET http://{{host}}/api/rest/tickets/token/ICP-icrc-TEST•RICH

### query tickets by receiver
GET http://{{host}}/api/rest/tickets/address/oqqew-3kok2-4ca2v-uwf4q-bykqb-yghly-kwet3-a5vqf-cu4ug-ztg4o-sqe


### query tickets by src_chain and sender with pagination alias
GET http://{{host}}/api/rest/tickets/bevm_testnet/address/null?limit=3&offset=0